### ISSUE TITLE
cant choose the sm64ex-coop unstable build

### ISSUE THREAD

**Issue by DRLatnern** [djoslin0/sm64ex-coop#232]
hello i want to be able to have the sm64ex-coop unstable build. but for some reason its not there, ive been looking everywhere for a reason that u dont want background gamepad and gamepad in sm64ex-coop coop, i just want the old build if that is fine..

**Comment by Amy54Desu** [comment]
You can use git checkout for an older version. But why would you want to go back to the unstable build? You cannot even use Discord Invites due to the party feature being deprecated. The latest version will also be required for coop.net too and if you don't like background gamepad, you can disable it.

**Comment by 12abz** [comment]
discord invites still can be used

**Comment by Isaac0-dev** [comment]
you can go back through commit history for the version you're looking for
