### ISSUE TITLE
sins/coss functions broken on arm architecture

### ISSUE THREAD

**Issue by EmeraldLoc** [djoslin0/sm64ex-coop#282]
If the value in the `sins` function is negative, it always return 0, and if the value in the `coss` function is negative, it always returns 1. It seems to cap the inputed number to 0 when inputting a negative number. 

Example mod:

```
hook_chat_command("goodsin", "s", function (msg)
    djui_chat_message_create(tostring(sins(35000)))
    return true
end)

hook_chat_command("badsin", "s", function (msg)
    djui_chat_message_create(tostring(sins(-35000)))
    return true
end)

hook_chat_command("goodcos", "s", function (msg)
    djui_chat_message_create(tostring(coss(35000)))
    return true
end)

hook_chat_command("badcos", "s", function (msg)
    djui_chat_message_create(tostring(coss(-35000)))
    return true
end)
```

From my testing, this bug is only on the arm architecture (very odd). I'm unsure if this is only a problem with lua.

Edit:

I of course am not close to skilled enough to make a pr for this, however, if this helps, according to chatgpt:

"This issue might be related to how negative numbers are handled when performing bitwise operations such as right shift (>>). On x86_64 architectures, the behavior of right shifting negative numbers is implementation-defined, meaning it can vary depending on the compiler and platform. However, on ARM architectures, the behavior is typically well-defined as arithmetic right shift, which preserves the sign bit.

The problem in your code arises because when you pass a negative number to the sins and coss functions, the (u16) (x) >> 4 operation is performed. If x is negative and the right shift is interpreted as an arithmetic shift, it could result in all bits being shifted to the right, effectively converting the negative number to zero."

**Comment by robertkirkman** [comment]
Hello EmeraldLoc. I have not experienced this bug since [December 2022](https://github.com/robertkirkman/sm64ex-coop/commit/7cc575ebad78a6e884096ec7396d5a7901753833). I guess the issue is lack of upstreaming. 
My implementation of the solution: Type of `x` in `smlua_func_coss()` and `smlua_func_sins()`  `f32`->`s16`. Please let me know if you have any questions.

**Comment by EmeraldLoc** [comment]
Interesting, i'll test that to see if that works. Only thing i'm tripping about is why would that work on the x86_64 architecture on not arm64?

**Comment by EmeraldLoc** [comment]
Sure enough that works! Thanks for the solution, unless you want to, i'll be sure to make a pr for this, thanks!

Also, if you have an answer to why the function works fine in the intel architecture, let me know, I am curious.

**Comment by robertkirkman** [comment]
@EmeraldLoc 
 I am happy to explain to you what I know. I can start with a basic summary to introduce you to multi-architecture Native code development. 

C and C++ are designed to be fully cross-platform and have a long history of use on almost every type of CPU, but sometimes, when these languages are compiled, there is an _error in the code that the compiler doesn't detect_ , or once in a while, there is a warning for it but the warning isn't enabled or isn't easily noticeable among other warnings. The most common error in this category is known as "**undefined behavior**" . Undefined behavior is defined as code that has a specific pattern in it that the language specification says is undefined behavior. The people who make compilers rely on the language specification to make sure they can all compile the same C and C++ to multiple CPU architectures, so people who make cross-platform apps also need to make sure most of the code is conformant to the language specification, in order to avoid creating undefined behavior.  When a program contains undefined behavior, at the point where the undefined behavior begins, it's generally said that it should be assumed absolutely anything could happen and the whole program could potentially crash or do something completely random. The basic point this sets up is, **a common real-world practical result of undefined behavior is slightly differing behavior between different CPU architectures, while most of the program confusingly continues to run normally.**

In this case, **the Undefined Behavior responsible for the bug you were experiencing** is this one: **[direct unguarded single cast from negative signed number to unsigned number](https://stackoverflow.com/questions/10541200/is-the-behaviour-of-casting-a-negative-double-to-unsigned-int-defined-in-the-c-s)**

If you isolate the part of the code of sm64ex-coop that you can see is behaving differently on x86 and ARM CPUs and simplify it until it becomes a **[Minimal Reproducible Example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)**, you get this:

```c
#include <stdio.h>

int main(void) {

    double floatingpoint = -1;

    // sm64ex-coop originally did this. 
    // Casting negative floating point number to 
    // unsigned integer is Undefined Behavior!
    printf("single cast: %d\n", 
        (unsigned short int) floatingpoint);

    // my code does something closer to this
    printf("double cast: %d\n", 
        (unsigned short int) (signed short int) floatingpoint);

    return 0;
}
```

If you compile and run this code on an x86 CPU and an ARM CPU, you will see they behave differently:

![image](https://github.com/djoslin0/sm64ex-coop/assets/31490854/78f17f04-b438-4468-ac5b-de39b2917196)

the `smlua_func_atan2s()` isn't affected because if you read it carefully you'll notice it works differently and it carefully handles negative numbers.

I used this [100% CPU accuracy full system ARM emulator](https://gist.github.com/robertkirkman/f79441c79811ad263f2f881f7864e793) to help me test and screenshot this demo in both an x86 environment and an ARM environment on the same system.

What I actually don't know about this at all and wouldn't be able to guess, is what happens if you compile the bugged version for x86, then run it on your Apple CPU with its Rosetta 2 hardware-assisted x86 emulator? :)

**Comment by EmeraldLoc** [comment]
Wow, thanks for the in depth answer, and for your time. Rosetta handles the behavior correctly, so compiling it for intel is a working solution, which is how I had tested it :)
