### ISSUE TITLE
Double Bowser in BITDW

### ISSUE THREAD

**Issue by anuserlol** [djoslin0/sm64ex-coop#40]
**Describe the bug**
If the two player grab Bowser at the same time, he gets cloned.

**To Reproduce**
1. Go to BITDW
2. Go to Bowser's platform
3. Grab Bowser at the same time as the other player
4. Profit

**Expected behavior**
Only one of the players should be able to grab Bowser at the same time.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/16540103/92660776-64cb9c80-f2fb-11ea-9c93-0b64bb46aa85.png)

**Additional context**
Honestly, we managed to do this trying to hurt each other lol

**Comment by anuserlol** [comment]
Same happens to the jumping block like the double bowser bug in BBH

**Comment by boardfish** [comment]
This is more out of curiosity than productivity, but is it possible to clone Bowser several times in this way?

**Comment by anuserlol** [comment]
I think that once you drop him one of them gets deleted, but I'm not 100% sure.

**Comment by boardfish** [comment]
I guess that would make this a purely visual glitch. I'm not sure how the game works, but I think what happens when you grab Bowser's tail is that the two models are joined together. When you let go, the throw animation plays and Bowser is launched from his position relative to where you were facing at the time of the throw. 

I think this bug probably happens as a result of a race condition between Mario (host) grabbing Bowser and Luigi (guest) grabbing Bowser at about the same time. The server shouldn't permit one of the players to grab Bowser and might need to adjust the player's position too.
