### ISSUE TITLE
Pause game on star cutscene, show both players the cutscene

### ISSUE THREAD

**Issue by anzz1** [djoslin0/sm64ex-coop#72]
**Enhancement suggestion**
Currently only the player who finishes the star mission requirement, sees the spawn-of-star cutscene and the other player does not. In the original single-player version the game pauses while this scene is playing. In coop it does not, but player is uncontrollable while the cutscene is playing (and even if he was controllable, the camera can be elsewhere). This leads to things like player dropping to lava after picking the last red coin in mid-air. Also levels like Tower of the Wing Cap are especially painful because of this.

Best way would be to pause the game when a star spawns, and show both players the cutscene. That would be how the original version works.

**To Reproduce**
1. Go to Bob-Omb Battlefield
2. Collect 8 red coins, Mario picks up the last coin.
3. Mario sees star spawn cutscene, but game is not paused and Mario is uncontrollable. Luigi does not see the cutscene and remains in control

**Comment by djoslin0** [comment]
Yeah I've been going back and forth on this idea. It's not fair dying because you lose control during the cutscene. It also isn't fun to be interrupted by the other player's cutscene when you're mid jump or something. I think you're right though, showing the cutscene for both is the lesser of two evils
